
services:
  crawl-data-container:
    image: apache/airflow:2.10.2-python3.12
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./project2-441416-142ca88fe3d7.json:/opt/airflow/project2-441416-142ca88fe3d7.json
    ports:
      - '9090:8080'
    restart: always
    environment:
      # - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db 
      # - AIRFLOW__CORE__EXECUTOR=SequentialExecutor  
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/project2-441416-142ca88fe3d7.json
    command: >
      bash -c "airflow db init && airflow db upgrade && airflow users create --username admin --password admin --firstname Trung --lastname Hieu --role Admin --email vudanhtrunghieu@gmail.com && airflow webserver & sleep 10 && airflow scheduler"
